

library(MendelianRandomization)
library(TwoSampleMR)
library(ieugwasr)
library(MRInstruments)
library(R.utils)



usethis::edit_r_environ()

ieugwasr::get_opengwas_jwt()

api_status()

user()

OPENGWAS_JWT=eyJhbGciOiJSUzI1NiIsImtpZCI6ImFwaS1qd3QiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJhcGkub3Blbmd3YXMuaW8iLCJhdWQiOiJhcGkub3Blbmd3YXMuaW8iLCJzdWIiOiIyNDAwMTFAc3IuZ3htdS5lZHUuY24iLCJpYXQiOjE3Mjc5NjQyMDgsImV4cCI6MTcyOTE3MzgwOH0.icQsY5QttEtyBbi99DdoIp2EqOLrTq572BvtwYZz4DVsJeGvdvC1QAug4LaMPa9_UmeMWwo1LMe1GfjJrnqUkGtBPEIRGJDdS_FfmZlgklZXIiPzzxg3oKBZPljCPv13oe25m-AWYTELHQTMpXG1bCdDpbh4_DV-73hvf5pVfmiEoiqStMIdyCeLKLb13Z2T74SJ5BXcwt4W6ecH6W7YekrxBQmt0V1gRydpK0ob9d3iI1GcXGLwpy0S1GJGny7KpjEWR5WBNIhmUCYFrP3lZfWfkmTCIMNsyW7hSN2mhA8mh2bpdRscVN-ajGq4ccm-xYz0qQU-cKaIgHlkEMzQ-g